name: Native Build (iOS)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cmake ninja

      - name: Build iOS native framework
        run: |
          chmod +x scripts/build_ios.sh
          OPENCV_ZIP_URL=https://github.com/masterjayr/ffi_practice/releases/download/v12.0/opencv2.framework.zip \
          scripts/build_ios.sh

      - name: Upload xcframework artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffi_practice_native_ios
          path: ios/Frameworks/ffi_practice_native.xcframework
